from cv2 import cv2

class Targets:
  character_indicator = cv2.imread('./images/targets/character_indicator.png')
  chest1 = cv2.imread('./images/targets/chest1.png')
  chest2 = cv2.imread('./images/targets/chest2.png')
  chest3 = cv2.imread('./images/targets/chest3.png')
  chest4 = cv2.imread('./images/targets/chest4.png')
  coin_rewards = cv2.imread('./images/targets/coin_rewards.png')
  connect_wallet_button = cv2.imread('./images/targets/connect_wallet_button.png')
  error = cv2.imread('./images/targets/error.png')
  full_screen_button = cv2.imread('./images/targets/full_screen_button.png')
  full_stamina = cv2.imread('./images/targets/full_stamina.png')
  go_back_arrow_button = cv2.imread('./images/targets/go_back_arrow_button.png')
  go_work_button = cv2.imread('./images/targets/go_work_button.png')
  green_bar = cv2.imread('./images/targets/green_bar.png')
  hero_icon = cv2.imread('./images/targets/hero_icon.png')
  home_button = cv2.imread('./images/targets/home_button.png')
  maintenance = cv2.imread('./images/targets/maintenance.png')
  metamask_cancel_button = cv2.imread('./images/targets/metamask_cancel_button.png')
  metamask_sign_button = cv2.imread('./images/targets/metamask_sign_button.png')
  metamask_unlock = cv2.imread('./images/targets/metamask_unlock.png')
  new_map_button = cv2.imread('./images/targets/new_map_button.png')
  ok_button = cv2.imread('./images/targets/ok_button.png')
  piece = cv2.imread('./images/targets/piece.png')
  puzzle = cv2.imread('./images/targets/puzzle.png')
  robot = cv2.imread('./images/targets/robot.png')
  slider = cv2.imread('./images/targets/slider.png')
  treasure_chest_button = cv2.imread('./images/targets/treasure_chest_button.png')
  treasure_hunt_banner = cv2.imread('./images/targets/treasure_hunt_banner.png')
  x_button = cv2.imread('./images/targets/x_button.png')